VIDEOS = {'Se Dar Char': [{'name': '01',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/1.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/1.mp4',
                       'genre': 'Se Dar Char'},
                       {'name': '02',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/2.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/2.mp4',
                       'genre': 'Se Dar Char'},
                       {'name': '03',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/3.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/3.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '04',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/4.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/4.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '05',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/5.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/5.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '06',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/6.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/6.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '07',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/7.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/7.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '08',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/8.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/8.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '09',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/9.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/9.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '10',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/10.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/10.mp4',
                       'genre': 'Se Dar Char'},
					   {'name': '11',
                       'thumb': 'https://preview.presstv.com/ifilm/da42445/11.png',
                       'video': 'https://preview.presstv.com/ifilm/da42445/11.mp4',
                       'genre': 'Se Dar Char'}
					   
                      ],
